version: "3"
services:
  envoy:
    image: envoyproxy/envoy-dev:e4955aed5694f9935d674419dbb364e744f697b4
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
