/**
 * @fileoverview gRPC-Web generated client stub for chatroom
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.1
// source: chatroom.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chatroom_pb from './chatroom_pb';
import * as common_pb from './common_pb';


export class ChatroomClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chatroom.Chatroom/SendMessage',
    grpcWeb.MethodType.UNARY,
    chatroom_pb.MessageRequest,
    common_pb.None,
    (request: chatroom_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    common_pb.None.deserializeBinary
  );

  sendMessage(
    request: chatroom_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<common_pb.None>;

  sendMessage(
    request: chatroom_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: common_pb.None) => void): grpcWeb.ClientReadableStream<common_pb.None>;

  sendMessage(
    request: chatroom_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: common_pb.None) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatroom.Chatroom/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatroom.Chatroom/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorReceiveMessages = new grpcWeb.MethodDescriptor(
    '/chatroom.Chatroom/ReceiveMessages',
    grpcWeb.MethodType.SERVER_STREAMING,
    common_pb.None,
    chatroom_pb.MessageResponse,
    (request: common_pb.None) => {
      return request.serializeBinary();
    },
    chatroom_pb.MessageResponse.deserializeBinary
  );

  receiveMessages(
    request: common_pb.None,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chatroom_pb.MessageResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatroom.Chatroom/ReceiveMessages',
      request,
      metadata || {},
      this.methodDescriptorReceiveMessages);
  }

}

