/**
 * @fileoverview gRPC-Web generated client stub for chatroom
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.1
// source: protos/chatroom.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protos_chatroom_pb from '../protos/chatroom_pb';


export class ChatroomClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chatroom.Chatroom/SendMessage',
    grpcWeb.MethodType.UNARY,
    protos_chatroom_pb.MessageRequest,
    protos_chatroom_pb.None,
    (request: protos_chatroom_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    protos_chatroom_pb.None.deserializeBinary
  );

  sendMessage(
    request: protos_chatroom_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<protos_chatroom_pb.None>;

  sendMessage(
    request: protos_chatroom_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_chatroom_pb.None) => void): grpcWeb.ClientReadableStream<protos_chatroom_pb.None>;

  sendMessage(
    request: protos_chatroom_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_chatroom_pb.None) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatroom.Chatroom/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatroom.Chatroom/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorReceiveMessages = new grpcWeb.MethodDescriptor(
    '/chatroom.Chatroom/ReceiveMessages',
    grpcWeb.MethodType.SERVER_STREAMING,
    protos_chatroom_pb.None,
    protos_chatroom_pb.MessageResponse,
    (request: protos_chatroom_pb.None) => {
      return request.serializeBinary();
    },
    protos_chatroom_pb.MessageResponse.deserializeBinary
  );

  receiveMessages(
    request: protos_chatroom_pb.None,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<protos_chatroom_pb.MessageResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatroom.Chatroom/ReceiveMessages',
      request,
      metadata || {},
      this.methodDescriptorReceiveMessages);
  }

  methodDescriptorGetUsers = new grpcWeb.MethodDescriptor(
    '/chatroom.Chatroom/GetUsers',
    grpcWeb.MethodType.SERVER_STREAMING,
    protos_chatroom_pb.None,
    protos_chatroom_pb.UserList,
    (request: protos_chatroom_pb.None) => {
      return request.serializeBinary();
    },
    protos_chatroom_pb.UserList.deserializeBinary
  );

  getUsers(
    request: protos_chatroom_pb.None,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<protos_chatroom_pb.UserList> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatroom.Chatroom/GetUsers',
      request,
      metadata || {},
      this.methodDescriptorGetUsers);
  }

}

